### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by fregante** [nachos/windowz#1]
I noticed that the npm package is empty, can you publish the latest?

https://registry.npmjs.org/windowz/-/windowz-0.0.0.tgz

**Comment by omrilitov** [comment]
Hi, happy to see someone interested in this package :) 
I'm gonna publish it later today, I'm not near a computer right now

**Comment by EladBezalel** [comment]
@bfred-it I'm interested, how did you find it? :stuck_out_tongue:

**Comment by fregante** [comment]
I looked for it, of course! :D I searched "list app windows", "get open windows" and then finally "open windows" which had a looot of popup-related and MSWin-related packages
https://npms.io/search?term=open+windows

**Comment by omrilitov** [comment]
Published under 0.1.0
